# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GHSPanel.ui'
#
# Created: Fri Jan 30 14:29:15 2015
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(962, 743)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(0, 0))
        MainWindow.setTabShape(QtGui.QTabWidget.Rounded)
        self.centralwidget = QtGui.QWidget(MainWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.auxiliaryCircuitDock = QtGui.QGroupBox(self.centralwidget)
        self.auxiliaryCircuitDock.setGeometry(QtCore.QRect(10, 20, 361, 531))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.auxiliaryCircuitDock.sizePolicy().hasHeightForWidth())
        self.auxiliaryCircuitDock.setSizePolicy(sizePolicy)
        self.auxiliaryCircuitDock.setTitle(_fromUtf8(""))
        self.auxiliaryCircuitDock.setAlignment(QtCore.Qt.AlignCenter)
        self.auxiliaryCircuitDock.setObjectName(_fromUtf8("auxiliaryCircuitDock"))
        self.lcdNumber_P1 = QtGui.QLCDNumber(self.auxiliaryCircuitDock)
        self.lcdNumber_P1.setGeometry(QtCore.QRect(110, 290, 64, 23))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.lcdNumber_P1.setFont(font)
        self.lcdNumber_P1.setStyleSheet(_fromUtf8("background-color: rgb(0, 0, 0);\n"
"color: rgb(0, 255, 0);\n"
"font: 10pt \"Arial\";"))
        self.lcdNumber_P1.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.lcdNumber_P1.setObjectName(_fromUtf8("lcdNumber_P1"))
        self.lcdNumber_P2 = QtGui.QLCDNumber(self.auxiliaryCircuitDock)
        self.lcdNumber_P2.setGeometry(QtCore.QRect(190, 290, 64, 23))
        self.lcdNumber_P2.setStyleSheet(_fromUtf8("background-color: rgb(0, 0, 0);\n"
"color: rgb(0, 255, 0);\n"
"font: 10pt \"Arial\";"))
        self.lcdNumber_P2.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.lcdNumber_P2.setObjectName(_fromUtf8("lcdNumber_P2"))
        self.lcdNumber_P3 = QtGui.QLCDNumber(self.auxiliaryCircuitDock)
        self.lcdNumber_P3.setGeometry(QtCore.QRect(270, 290, 64, 23))
        self.lcdNumber_P3.setStyleSheet(_fromUtf8("background-color: rgb(0, 0, 0);\n"
"color: rgb(0, 255, 0);\n"
"font: 10pt \"Arial\";"))
        self.lcdNumber_P3.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.lcdNumber_P3.setObjectName(_fromUtf8("lcdNumber_P3"))
        self.label_P1 = QtGui.QLabel(self.auxiliaryCircuitDock)
        self.label_P1.setGeometry(QtCore.QRect(110, 270, 21, 17))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setPointSize(8)
        self.label_P1.setFont(font)
        self.label_P1.setObjectName(_fromUtf8("label_P1"))
        self.label_P2 = QtGui.QLabel(self.auxiliaryCircuitDock)
        self.label_P2.setGeometry(QtCore.QRect(190, 270, 21, 17))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setPointSize(8)
        self.label_P2.setFont(font)
        self.label_P2.setObjectName(_fromUtf8("label_P2"))
        self.label_P3 = QtGui.QLabel(self.auxiliaryCircuitDock)
        self.label_P3.setGeometry(QtCore.QRect(270, 270, 21, 17))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(8)
        self.label_P3.setFont(font)
        self.label_P3.setObjectName(_fromUtf8("label_P3"))
        self.radioButton_A1 = QtGui.QRadioButton(self.auxiliaryCircuitDock)
        self.radioButton_A1.setEnabled(False)
        self.radioButton_A1.setGeometry(QtCore.QRect(200, 210, 51, 22))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setPointSize(8)
        self.radioButton_A1.setFont(font)
        self.radioButton_A1.setMouseTracking(False)
        self.radioButton_A1.setFocusPolicy(QtCore.Qt.NoFocus)
        self.radioButton_A1.setCheckable(True)
        self.radioButton_A1.setChecked(False)
        self.radioButton_A1.setAutoExclusive(False)
        self.radioButton_A1.setObjectName(_fromUtf8("radioButton_A1"))
        self.line = QtGui.QFrame(self.auxiliaryCircuitDock)
        self.line.setEnabled(True)
        self.line.setGeometry(QtCore.QRect(220, 240, 4, 41))
        self.line.setAutoFillBackground(False)
        self.line.setStyleSheet(_fromUtf8("color: rgb(255, 255, 0);\n"
"border-color: rgb(255, 255, 0);\n"
"background-color: rgb(255, 255, 0);"))
        self.line.setFrameShadow(QtGui.QFrame.Plain)
        self.line.setLineWidth(0)
        self.line.setMidLineWidth(0)
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.line_2 = QtGui.QFrame(self.auxiliaryCircuitDock)
        self.line_2.setEnabled(True)
        self.line_2.setGeometry(QtCore.QRect(220, 10, 4, 191))
        self.line_2.setAutoFillBackground(False)
        self.line_2.setStyleSheet(_fromUtf8("color: rgb(255, 255, 0);\n"
"border-color: rgb(255, 255, 0);\n"
"background-color: rgb(255, 255, 0);"))
        self.line_2.setFrameShadow(QtGui.QFrame.Plain)
        self.line_2.setLineWidth(0)
        self.line_2.setMidLineWidth(0)
        self.line_2.setFrameShape(QtGui.QFrame.VLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.line_3 = QtGui.QFrame(self.auxiliaryCircuitDock)
        self.line_3.setEnabled(True)
        self.line_3.setGeometry(QtCore.QRect(140, 10, 4, 271))
        self.line_3.setAutoFillBackground(False)
        self.line_3.setStyleSheet(_fromUtf8("color: rgb(255, 255, 0);\n"
"border-color: rgb(255, 255, 0);\n"
"background-color: rgb(255, 255, 0);"))
        self.line_3.setFrameShadow(QtGui.QFrame.Plain)
        self.line_3.setLineWidth(0)
        self.line_3.setMidLineWidth(0)
        self.line_3.setFrameShape(QtGui.QFrame.VLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.line_4 = QtGui.QFrame(self.auxiliaryCircuitDock)
        self.line_4.setEnabled(True)
        self.line_4.setGeometry(QtCore.QRect(300, 240, 4, 41))
        self.line_4.setAutoFillBackground(False)
        self.line_4.setStyleSheet(_fromUtf8("color: rgb(255, 255, 0);\n"
"border-color: rgb(255, 255, 0);\n"
"background-color: rgb(255, 255, 0);"))
        self.line_4.setFrameShadow(QtGui.QFrame.Plain)
        self.line_4.setLineWidth(0)
        self.line_4.setMidLineWidth(0)
        self.line_4.setFrameShape(QtGui.QFrame.VLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.radioButton_A2 = QtGui.QRadioButton(self.auxiliaryCircuitDock)
        self.radioButton_A2.setEnabled(False)
        self.radioButton_A2.setGeometry(QtCore.QRect(280, 210, 51, 22))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setPointSize(8)
        self.radioButton_A2.setFont(font)
        self.radioButton_A2.setMouseTracking(False)
        self.radioButton_A2.setFocusPolicy(QtCore.Qt.NoFocus)
        self.radioButton_A2.setAutoExclusive(False)
        self.radioButton_A2.setObjectName(_fromUtf8("radioButton_A2"))
        self.line_5 = QtGui.QFrame(self.auxiliaryCircuitDock)
        self.line_5.setEnabled(True)
        self.line_5.setGeometry(QtCore.QRect(300, 180, 4, 21))
        self.line_5.setAutoFillBackground(False)
        self.line_5.setStyleSheet(_fromUtf8("color: rgb(255, 255, 0);\n"
"border-color: rgb(255, 255, 0);\n"
"background-color: rgb(255, 255, 0);"))
        self.line_5.setFrameShadow(QtGui.QFrame.Plain)
        self.line_5.setLineWidth(0)
        self.line_5.setMidLineWidth(0)
        self.line_5.setFrameShape(QtGui.QFrame.VLine)
        self.line_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_5.setObjectName(_fromUtf8("line_5"))
        self.radioButton_S5 = QtGui.QRadioButton(self.auxiliaryCircuitDock)
        self.radioButton_S5.setEnabled(False)
        self.radioButton_S5.setGeometry(QtCore.QRect(280, 150, 51, 22))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setPointSize(8)
        self.radioButton_S5.setFont(font)
        self.radioButton_S5.setMouseTracking(False)
        self.radioButton_S5.setFocusPolicy(QtCore.Qt.NoFocus)
        self.radioButton_S5.setCheckable(True)
        self.radioButton_S5.setAutoExclusive(False)
        self.radioButton_S5.setObjectName(_fromUtf8("radioButton_S5"))
        self.line_6 = QtGui.QFrame(self.auxiliaryCircuitDock)
        self.line_6.setEnabled(True)
        self.line_6.setGeometry(QtCore.QRect(300, 120, 4, 21))
        self.line_6.setAutoFillBackground(False)
        self.line_6.setStyleSheet(_fromUtf8("color: rgb(255, 255, 0);\n"
"border-color: rgb(255, 255, 0);\n"
"background-color: rgb(255, 255, 0);"))
        self.line_6.setFrameShadow(QtGui.QFrame.Plain)
        self.line_6.setLineWidth(0)
        self.line_6.setMidLineWidth(0)
        self.line_6.setFrameShape(QtGui.QFrame.VLine)
        self.line_6.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_6.setObjectName(_fromUtf8("line_6"))
        self.radioButton_A0 = QtGui.QRadioButton(self.auxiliaryCircuitDock)
        self.radioButton_A0.setEnabled(False)
        self.radioButton_A0.setGeometry(QtCore.QRect(280, 90, 51, 22))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setPointSize(8)
        self.radioButton_A0.setFont(font)
        self.radioButton_A0.setMouseTracking(False)
        self.radioButton_A0.setFocusPolicy(QtCore.Qt.NoFocus)
        self.radioButton_A0.setStyleSheet(_fromUtf8(""))
        self.radioButton_A0.setCheckable(True)
        self.radioButton_A0.setAutoExclusive(False)
        self.radioButton_A0.setObjectName(_fromUtf8("radioButton_A0"))
        self.line_9 = QtGui.QFrame(self.auxiliaryCircuitDock)
        self.line_9.setEnabled(True)
        self.line_9.setGeometry(QtCore.QRect(300, 320, 4, 111))
        self.line_9.setAutoFillBackground(False)
        self.line_9.setStyleSheet(_fromUtf8("color: rgb(255, 255, 0);\n"
"border-color: rgb(255, 255, 0);\n"
"background-color: rgb(255, 255, 0);"))
        self.line_9.setFrameShadow(QtGui.QFrame.Plain)
        self.line_9.setLineWidth(0)
        self.line_9.setMidLineWidth(0)
        self.line_9.setFrameShape(QtGui.QFrame.VLine)
        self.line_9.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_9.setObjectName(_fromUtf8("line_9"))
        self.line_10 = QtGui.QFrame(self.auxiliaryCircuitDock)
        self.line_10.setEnabled(True)
        self.line_10.setGeometry(QtCore.QRect(220, 320, 4, 111))
        self.line_10.setAutoFillBackground(False)
        self.line_10.setStyleSheet(_fromUtf8("color: rgb(255, 255, 0);\n"
"border-color: rgb(255, 255, 0);\n"
"background-color: rgb(255, 255, 0);"))
        self.line_10.setFrameShadow(QtGui.QFrame.Plain)
        self.line_10.setLineWidth(0)
        self.line_10.setMidLineWidth(0)
        self.line_10.setFrameShape(QtGui.QFrame.VLine)
        self.line_10.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_10.setObjectName(_fromUtf8("line_10"))
        self.line_11 = QtGui.QFrame(self.auxiliaryCircuitDock)
        self.line_11.setEnabled(True)
        self.line_11.setGeometry(QtCore.QRect(140, 320, 4, 111))
        self.line_11.setAutoFillBackground(False)
        self.line_11.setStyleSheet(_fromUtf8("color: rgb(255, 255, 0);\n"
"border-color: rgb(255, 255, 0);\n"
"background-color: rgb(255, 255, 0);"))
        self.line_11.setFrameShadow(QtGui.QFrame.Plain)
        self.line_11.setLineWidth(0)
        self.line_11.setMidLineWidth(0)
        self.line_11.setFrameShape(QtGui.QFrame.VLine)
        self.line_11.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_11.setObjectName(_fromUtf8("line_11"))
        self.radioButton_A4 = QtGui.QRadioButton(self.auxiliaryCircuitDock)
        self.radioButton_A4.setEnabled(False)
        self.radioButton_A4.setGeometry(QtCore.QRect(160, 380, 41, 22))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setPointSize(8)
        self.radioButton_A4.setFont(font)
        self.radioButton_A4.setMouseTracking(False)
        self.radioButton_A4.setFocusPolicy(QtCore.Qt.NoFocus)
        self.radioButton_A4.setAutoExclusive(False)
        self.radioButton_A4.setObjectName(_fromUtf8("radioButton_A4"))
        self.radioButton_A5 = QtGui.QRadioButton(self.auxiliaryCircuitDock)
        self.radioButton_A5.setEnabled(False)
        self.radioButton_A5.setGeometry(QtCore.QRect(240, 380, 51, 22))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setPointSize(8)
        self.radioButton_A5.setFont(font)
        self.radioButton_A5.setMouseTracking(False)
        self.radioButton_A5.setFocusPolicy(QtCore.Qt.NoFocus)
        self.radioButton_A5.setAutoExclusive(False)
        self.radioButton_A5.setObjectName(_fromUtf8("radioButton_A5"))
        self.radioButton_A3 = QtGui.QRadioButton(self.auxiliaryCircuitDock)
        self.radioButton_A3.setEnabled(False)
        self.radioButton_A3.setGeometry(QtCore.QRect(70, 380, 51, 22))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setPointSize(8)
        self.radioButton_A3.setFont(font)
        self.radioButton_A3.setMouseTracking(False)
        self.radioButton_A3.setFocusPolicy(QtCore.Qt.NoFocus)
        self.radioButton_A3.setAutoExclusive(False)
        self.radioButton_A3.setObjectName(_fromUtf8("radioButton_A3"))
        self.line_12 = QtGui.QFrame(self.auxiliaryCircuitDock)
        self.line_12.setEnabled(True)
        self.line_12.setGeometry(QtCore.QRect(120, 390, 31, 4))
        self.line_12.setAutoFillBackground(False)
        self.line_12.setStyleSheet(_fromUtf8("color: rgb(255, 255, 0);\n"
"border-color: rgb(255, 255, 0);\n"
"background-color: rgb(255, 255, 0);"))
        self.line_12.setFrameShadow(QtGui.QFrame.Plain)
        self.line_12.setLineWidth(0)
        self.line_12.setMidLineWidth(0)
        self.line_12.setFrameShape(QtGui.QFrame.HLine)
        self.line_12.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_12.setObjectName(_fromUtf8("line_12"))
        self.line_13 = QtGui.QFrame(self.auxiliaryCircuitDock)
        self.line_13.setEnabled(True)
        self.line_13.setGeometry(QtCore.QRect(210, 390, 27, 4))
        self.line_13.setAutoFillBackground(False)
        self.line_13.setStyleSheet(_fromUtf8("color: rgb(255, 255, 0);\n"
"border-color: rgb(255, 255, 0);\n"
"background-color: rgb(255, 255, 0);"))
        self.line_13.setFrameShadow(QtGui.QFrame.Plain)
        self.line_13.setLineWidth(0)
        self.line_13.setMidLineWidth(0)
        self.line_13.setFrameShape(QtGui.QFrame.HLine)
        self.line_13.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_13.setObjectName(_fromUtf8("line_13"))
        self.line_14 = QtGui.QFrame(self.auxiliaryCircuitDock)
        self.line_14.setEnabled(True)
        self.line_14.setGeometry(QtCore.QRect(290, 390, 10, 4))
        self.line_14.setAutoFillBackground(False)
        self.line_14.setStyleSheet(_fromUtf8("color: rgb(255, 255, 0);\n"
"border-color: rgb(255, 255, 0);\n"
"background-color: rgb(255, 255, 0);"))
        self.line_14.setFrameShadow(QtGui.QFrame.Plain)
        self.line_14.setLineWidth(0)
        self.line_14.setMidLineWidth(0)
        self.line_14.setFrameShape(QtGui.QFrame.HLine)
        self.line_14.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_14.setObjectName(_fromUtf8("line_14"))
        self.radioButton_A6 = QtGui.QRadioButton(self.auxiliaryCircuitDock)
        self.radioButton_A6.setEnabled(False)
        self.radioButton_A6.setGeometry(QtCore.QRect(120, 440, 51, 22))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setPointSize(8)
        self.radioButton_A6.setFont(font)
        self.radioButton_A6.setMouseTracking(False)
        self.radioButton_A6.setFocusPolicy(QtCore.Qt.NoFocus)
        self.radioButton_A6.setAutoExclusive(False)
        self.radioButton_A6.setObjectName(_fromUtf8("radioButton_A6"))
        self.radioButton_A7 = QtGui.QRadioButton(self.auxiliaryCircuitDock)
        self.radioButton_A7.setEnabled(False)
        self.radioButton_A7.setGeometry(QtCore.QRect(200, 440, 51, 22))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setPointSize(8)
        self.radioButton_A7.setFont(font)
        self.radioButton_A7.setMouseTracking(False)
        self.radioButton_A7.setFocusPolicy(QtCore.Qt.NoFocus)
        self.radioButton_A7.setAutoExclusive(False)
        self.radioButton_A7.setObjectName(_fromUtf8("radioButton_A7"))
        self.radioButton_A8 = QtGui.QRadioButton(self.auxiliaryCircuitDock)
        self.radioButton_A8.setEnabled(False)
        self.radioButton_A8.setGeometry(QtCore.QRect(280, 440, 51, 22))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setPointSize(8)
        self.radioButton_A8.setFont(font)
        self.radioButton_A8.setMouseTracking(False)
        self.radioButton_A8.setFocusPolicy(QtCore.Qt.NoFocus)
        self.radioButton_A8.setAutoExclusive(False)
        self.radioButton_A8.setObjectName(_fromUtf8("radioButton_A8"))
        self.line_7 = QtGui.QFrame(self.auxiliaryCircuitDock)
        self.line_7.setEnabled(True)
        self.line_7.setGeometry(QtCore.QRect(140, 470, 4, 31))
        self.line_7.setAutoFillBackground(False)
        self.line_7.setStyleSheet(_fromUtf8("color: rgb(255, 255, 0);\n"
"border-color: rgb(255, 255, 0);\n"
"background-color: rgb(255, 255, 0);"))
        self.line_7.setFrameShadow(QtGui.QFrame.Plain)
        self.line_7.setLineWidth(0)
        self.line_7.setMidLineWidth(0)
        self.line_7.setFrameShape(QtGui.QFrame.VLine)
        self.line_7.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_7.setObjectName(_fromUtf8("line_7"))
        self.line_8 = QtGui.QFrame(self.auxiliaryCircuitDock)
        self.line_8.setEnabled(True)
        self.line_8.setGeometry(QtCore.QRect(220, 470, 4, 31))
        self.line_8.setAutoFillBackground(False)
        self.line_8.setStyleSheet(_fromUtf8("color: rgb(255, 255, 0);\n"
"border-color: rgb(255, 255, 0);\n"
"background-color: rgb(255, 255, 0);"))
        self.line_8.setFrameShadow(QtGui.QFrame.Plain)
        self.line_8.setLineWidth(0)
        self.line_8.setMidLineWidth(0)
        self.line_8.setFrameShape(QtGui.QFrame.VLine)
        self.line_8.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_8.setObjectName(_fromUtf8("line_8"))
        self.line_15 = QtGui.QFrame(self.auxiliaryCircuitDock)
        self.line_15.setEnabled(True)
        self.line_15.setGeometry(QtCore.QRect(300, 470, 4, 34))
        self.line_15.setAutoFillBackground(False)
        self.line_15.setStyleSheet(_fromUtf8("color: rgb(255, 255, 0);\n"
"border-color: rgb(255, 255, 0);\n"
"background-color: rgb(255, 255, 0);"))
        self.line_15.setFrameShadow(QtGui.QFrame.Plain)
        self.line_15.setLineWidth(0)
        self.line_15.setMidLineWidth(0)
        self.line_15.setFrameShape(QtGui.QFrame.VLine)
        self.line_15.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_15.setObjectName(_fromUtf8("line_15"))
        self.line_16 = QtGui.QFrame(self.auxiliaryCircuitDock)
        self.line_16.setEnabled(True)
        self.line_16.setGeometry(QtCore.QRect(120, 500, 181, 4))
        self.line_16.setAutoFillBackground(False)
        self.line_16.setStyleSheet(_fromUtf8("color: rgb(255, 255, 0);\n"
"border-color: rgb(255, 255, 0);\n"
"background-color: rgb(255, 255, 0);"))
        self.line_16.setFrameShadow(QtGui.QFrame.Plain)
        self.line_16.setLineWidth(0)
        self.line_16.setMidLineWidth(0)
        self.line_16.setFrameShape(QtGui.QFrame.HLine)
        self.line_16.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_16.setObjectName(_fromUtf8("line_16"))
        self.radioButton_S4 = QtGui.QRadioButton(self.auxiliaryCircuitDock)
        self.radioButton_S4.setEnabled(False)
        self.radioButton_S4.setGeometry(QtCore.QRect(70, 490, 41, 22))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setPointSize(8)
        self.radioButton_S4.setFont(font)
        self.radioButton_S4.setMouseTracking(False)
        self.radioButton_S4.setFocusPolicy(QtCore.Qt.NoFocus)
        self.radioButton_S4.setAutoExclusive(False)
        self.radioButton_S4.setObjectName(_fromUtf8("radioButton_S4"))
        self.line_17 = QtGui.QFrame(self.auxiliaryCircuitDock)
        self.line_17.setEnabled(True)
        self.line_17.setGeometry(QtCore.QRect(30, 500, 31, 4))
        self.line_17.setAutoFillBackground(False)
        self.line_17.setStyleSheet(_fromUtf8("color: rgb(255, 255, 0);\n"
"border-color: rgb(255, 255, 0);\n"
"background-color: rgb(255, 255, 0);"))
        self.line_17.setFrameShadow(QtGui.QFrame.Plain)
        self.line_17.setLineWidth(0)
        self.line_17.setMidLineWidth(0)
        self.line_17.setFrameShape(QtGui.QFrame.HLine)
        self.line_17.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_17.setObjectName(_fromUtf8("line_17"))
        self.line_18 = QtGui.QFrame(self.auxiliaryCircuitDock)
        self.line_18.setEnabled(True)
        self.line_18.setGeometry(QtCore.QRect(30, 390, 31, 4))
        self.line_18.setAutoFillBackground(False)
        self.line_18.setStyleSheet(_fromUtf8("color: rgb(255, 255, 0);\n"
"border-color: rgb(255, 255, 0);\n"
"background-color: rgb(255, 255, 0);"))
        self.line_18.setFrameShadow(QtGui.QFrame.Plain)
        self.line_18.setLineWidth(0)
        self.line_18.setMidLineWidth(0)
        self.line_18.setFrameShape(QtGui.QFrame.HLine)
        self.line_18.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_18.setObjectName(_fromUtf8("line_18"))
        self.line_19 = QtGui.QFrame(self.auxiliaryCircuitDock)
        self.line_19.setEnabled(True)
        self.line_19.setGeometry(QtCore.QRect(30, 10, 4, 491))
        self.line_19.setAutoFillBackground(False)
        self.line_19.setStyleSheet(_fromUtf8("color: rgb(255, 255, 0);\n"
"border-color: rgb(255, 255, 0);\n"
"background-color: rgb(255, 255, 0);"))
        self.line_19.setFrameShadow(QtGui.QFrame.Plain)
        self.line_19.setLineWidth(0)
        self.line_19.setMidLineWidth(0)
        self.line_19.setFrameShape(QtGui.QFrame.VLine)
        self.line_19.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_19.setObjectName(_fromUtf8("line_19"))
        self.line_55 = QtGui.QFrame(self.auxiliaryCircuitDock)
        self.line_55.setEnabled(True)
        self.line_55.setGeometry(QtCore.QRect(300, 10, 4, 71))
        self.line_55.setAutoFillBackground(False)
        self.line_55.setStyleSheet(_fromUtf8("color: rgb(255, 255, 0);\n"
"border-color: rgb(255, 255, 0);\n"
"background-color: rgb(255, 255, 0);"))
        self.line_55.setFrameShadow(QtGui.QFrame.Plain)
        self.line_55.setLineWidth(0)
        self.line_55.setMidLineWidth(0)
        self.line_55.setFrameShape(QtGui.QFrame.VLine)
        self.line_55.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_55.setObjectName(_fromUtf8("line_55"))
        self.label_5 = QtGui.QLabel(self.auxiliaryCircuitDock)
        self.label_5.setGeometry(QtCore.QRect(40, 20, 61, 17))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setPointSize(6)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.label_6 = QtGui.QLabel(self.auxiliaryCircuitDock)
        self.label_6.setGeometry(QtCore.QRect(150, 20, 61, 17))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setPointSize(6)
        font.setItalic(False)
        self.label_6.setFont(font)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.label_7 = QtGui.QLabel(self.auxiliaryCircuitDock)
        self.label_7.setGeometry(QtCore.QRect(230, 20, 61, 17))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setPointSize(6)
        self.label_7.setFont(font)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.label_8 = QtGui.QLabel(self.auxiliaryCircuitDock)
        self.label_8.setGeometry(QtCore.QRect(310, 0, 51, 17))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setPointSize(6)
        self.label_8.setFont(font)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.mixtureCircuitDock = QtGui.QGroupBox(self.centralwidget)
        self.mixtureCircuitDock.setGeometry(QtCore.QRect(470, 20, 481, 531))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mixtureCircuitDock.sizePolicy().hasHeightForWidth())
        self.mixtureCircuitDock.setSizePolicy(sizePolicy)
        self.mixtureCircuitDock.setTitle(_fromUtf8(""))
        self.mixtureCircuitDock.setAlignment(QtCore.Qt.AlignCenter)
        self.mixtureCircuitDock.setObjectName(_fromUtf8("mixtureCircuitDock"))
        self.lcdNumber_P4 = QtGui.QLCDNumber(self.mixtureCircuitDock)
        self.lcdNumber_P4.setGeometry(QtCore.QRect(20, 210, 64, 23))
        self.lcdNumber_P4.setStyleSheet(_fromUtf8("background-color: rgb(0, 0, 0);\n"
"color: rgb(0, 255, 0);\n"
"font: 10pt \"Arial\";"))
        self.lcdNumber_P4.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.lcdNumber_P4.setObjectName(_fromUtf8("lcdNumber_P4"))
        self.lcdNumber_P5 = QtGui.QLCDNumber(self.mixtureCircuitDock)
        self.lcdNumber_P5.setGeometry(QtCore.QRect(200, 490, 64, 23))
        self.lcdNumber_P5.setStyleSheet(_fromUtf8("background-color: rgb(0, 0, 0);\n"
"color: rgb(0, 255, 0);\n"
"font: 10pt \"Arial\";"))
        self.lcdNumber_P5.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.lcdNumber_P5.setObjectName(_fromUtf8("lcdNumber_P5"))
        self.lcdNumber_P6 = QtGui.QLCDNumber(self.mixtureCircuitDock)
        self.lcdNumber_P6.setGeometry(QtCore.QRect(140, 310, 64, 23))
        self.lcdNumber_P6.setStyleSheet(_fromUtf8("background-color: rgb(0, 0, 0);\n"
"color: rgb(0, 255, 0);\n"
"font: 10pt \"Arial\";"))
        self.lcdNumber_P6.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.lcdNumber_P6.setObjectName(_fromUtf8("lcdNumber_P6"))
        self.lcdNumber_P7 = QtGui.QLCDNumber(self.mixtureCircuitDock)
        self.lcdNumber_P7.setGeometry(QtCore.QRect(140, 370, 64, 23))
        self.lcdNumber_P7.setStyleSheet(_fromUtf8("background-color: rgb(0, 0, 0);\n"
"color: rgb(0, 255, 0);\n"
"font: 10pt \"Arial\";"))
        self.lcdNumber_P7.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.lcdNumber_P7.setObjectName(_fromUtf8("lcdNumber_P7"))
        self.lcdNumber_P8 = QtGui.QLCDNumber(self.mixtureCircuitDock)
        self.lcdNumber_P8.setGeometry(QtCore.QRect(260, 200, 64, 23))
        self.lcdNumber_P8.setStyleSheet(_fromUtf8("background-color: rgb(0, 0, 0);\n"
"color: rgb(0, 255, 0);\n"
"font: 10pt \"Arial\";"))
        self.lcdNumber_P8.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.lcdNumber_P8.setObjectName(_fromUtf8("lcdNumber_P8"))
        self.label_P4 = QtGui.QLabel(self.mixtureCircuitDock)
        self.label_P4.setGeometry(QtCore.QRect(20, 190, 21, 17))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setPointSize(9)
        self.label_P4.setFont(font)
        self.label_P4.setObjectName(_fromUtf8("label_P4"))
        self.label_P5 = QtGui.QLabel(self.mixtureCircuitDock)
        self.label_P5.setGeometry(QtCore.QRect(200, 470, 21, 17))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setPointSize(8)
        self.label_P5.setFont(font)
        self.label_P5.setObjectName(_fromUtf8("label_P5"))
        self.label_P6 = QtGui.QLabel(self.mixtureCircuitDock)
        self.label_P6.setGeometry(QtCore.QRect(140, 290, 71, 17))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setPointSize(8)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.label_P6.setFont(font)
        self.label_P6.setObjectName(_fromUtf8("label_P6"))
        self.label_P7 = QtGui.QLabel(self.mixtureCircuitDock)
        self.label_P7.setGeometry(QtCore.QRect(140, 350, 71, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setPointSize(8)
        self.label_P7.setFont(font)
        self.label_P7.setObjectName(_fromUtf8("label_P7"))
        self.label_P8 = QtGui.QLabel(self.mixtureCircuitDock)
        self.label_P8.setGeometry(QtCore.QRect(330, 205, 41, 17))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setPointSize(8)
        self.label_P8.setFont(font)
        self.label_P8.setObjectName(_fromUtf8("label_P8"))
        self.line_20 = QtGui.QFrame(self.mixtureCircuitDock)
        self.line_20.setEnabled(True)
        self.line_20.setGeometry(QtCore.QRect(50, 240, 4, 121))
        self.line_20.setAutoFillBackground(False)
        self.line_20.setStyleSheet(_fromUtf8("color: rgb(0, 170, 0);\n"
"background-color: rgb(0, 170, 0);\n"
"border-color: rgb(0, 170, 0);"))
        self.line_20.setFrameShadow(QtGui.QFrame.Plain)
        self.line_20.setLineWidth(0)
        self.line_20.setMidLineWidth(0)
        self.line_20.setFrameShape(QtGui.QFrame.VLine)
        self.line_20.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_20.setObjectName(_fromUtf8("line_20"))
        self.radioButton_2 = QtGui.QRadioButton(self.mixtureCircuitDock)
        self.radioButton_2.setEnabled(False)
        self.radioButton_2.setGeometry(QtCore.QRect(30, 370, 41, 22))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setPointSize(8)
        self.radioButton_2.setFont(font)
        self.radioButton_2.setMouseTracking(False)
        self.radioButton_2.setFocusPolicy(QtCore.Qt.NoFocus)
        self.radioButton_2.setAutoExclusive(False)
        self.radioButton_2.setObjectName(_fromUtf8("radioButton_2"))
        self.line_21 = QtGui.QFrame(self.mixtureCircuitDock)
        self.line_21.setEnabled(True)
        self.line_21.setGeometry(QtCore.QRect(50, 400, 4, 41))
        self.line_21.setAutoFillBackground(False)
        self.line_21.setStyleSheet(_fromUtf8("color: rgb(0, 170, 0);\n"
"background-color: rgb(0, 170, 0);\n"
"border-color: rgb(0, 170, 0);"))
        self.line_21.setFrameShadow(QtGui.QFrame.Plain)
        self.line_21.setLineWidth(0)
        self.line_21.setMidLineWidth(0)
        self.line_21.setFrameShape(QtGui.QFrame.VLine)
        self.line_21.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_21.setObjectName(_fromUtf8("line_21"))
        self.radioButton_3 = QtGui.QRadioButton(self.mixtureCircuitDock)
        self.radioButton_3.setEnabled(False)
        self.radioButton_3.setGeometry(QtCore.QRect(30, 450, 41, 22))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setPointSize(8)
        self.radioButton_3.setFont(font)
        self.radioButton_3.setMouseTracking(False)
        self.radioButton_3.setFocusPolicy(QtCore.Qt.NoFocus)
        self.radioButton_3.setAutoExclusive(False)
        self.radioButton_3.setObjectName(_fromUtf8("radioButton_3"))
        self.line_22 = QtGui.QFrame(self.mixtureCircuitDock)
        self.line_22.setEnabled(True)
        self.line_22.setGeometry(QtCore.QRect(50, 480, 4, 24))
        self.line_22.setAutoFillBackground(False)
        self.line_22.setStyleSheet(_fromUtf8("color: rgb(0, 170, 0);\n"
"background-color: rgb(0, 170, 0);\n"
"border-color: rgb(0, 170, 0);"))
        self.line_22.setFrameShadow(QtGui.QFrame.Plain)
        self.line_22.setLineWidth(0)
        self.line_22.setMidLineWidth(0)
        self.line_22.setFrameShape(QtGui.QFrame.VLine)
        self.line_22.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_22.setObjectName(_fromUtf8("line_22"))
        self.line_23 = QtGui.QFrame(self.mixtureCircuitDock)
        self.line_23.setEnabled(True)
        self.line_23.setGeometry(QtCore.QRect(50, 500, 51, 4))
        self.line_23.setAutoFillBackground(False)
        self.line_23.setStyleSheet(_fromUtf8("color: rgb(0, 170, 0);\n"
"background-color: rgb(0, 170, 0);\n"
"border-color: rgb(0, 170, 0);"))
        self.line_23.setFrameShadow(QtGui.QFrame.Plain)
        self.line_23.setLineWidth(0)
        self.line_23.setMidLineWidth(0)
        self.line_23.setFrameShape(QtGui.QFrame.HLine)
        self.line_23.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_23.setObjectName(_fromUtf8("line_23"))
        self.radioButton_S3 = QtGui.QRadioButton(self.mixtureCircuitDock)
        self.radioButton_S3.setEnabled(False)
        self.radioButton_S3.setGeometry(QtCore.QRect(110, 490, 51, 22))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setPointSize(8)
        self.radioButton_S3.setFont(font)
        self.radioButton_S3.setMouseTracking(False)
        self.radioButton_S3.setFocusPolicy(QtCore.Qt.NoFocus)
        self.radioButton_S3.setAutoExclusive(False)
        self.radioButton_S3.setObjectName(_fromUtf8("radioButton_S3"))
        self.line_24 = QtGui.QFrame(self.mixtureCircuitDock)
        self.line_24.setEnabled(True)
        self.line_24.setGeometry(QtCore.QRect(160, 500, 31, 4))
        self.line_24.setAutoFillBackground(False)
        self.line_24.setStyleSheet(_fromUtf8("color: rgb(0, 170, 0);\n"
"background-color: rgb(0, 170, 0);\n"
"border-color: rgb(0, 170, 0);"))
        self.line_24.setFrameShadow(QtGui.QFrame.Plain)
        self.line_24.setLineWidth(0)
        self.line_24.setMidLineWidth(0)
        self.line_24.setFrameShape(QtGui.QFrame.HLine)
        self.line_24.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_24.setObjectName(_fromUtf8("line_24"))
        self.line_25 = QtGui.QFrame(self.mixtureCircuitDock)
        self.line_25.setEnabled(True)
        self.line_25.setGeometry(QtCore.QRect(270, 500, 181, 4))
        self.line_25.setAutoFillBackground(False)
        self.line_25.setStyleSheet(_fromUtf8("color: rgb(0, 170, 0);\n"
"background-color: rgb(0, 170, 0);\n"
"border-color: rgb(0, 170, 0);"))
        self.line_25.setFrameShadow(QtGui.QFrame.Plain)
        self.line_25.setLineWidth(0)
        self.line_25.setMidLineWidth(0)
        self.line_25.setFrameShape(QtGui.QFrame.HLine)
        self.line_25.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_25.setObjectName(_fromUtf8("line_25"))
        self.line_26 = QtGui.QFrame(self.mixtureCircuitDock)
        self.line_26.setEnabled(True)
        self.line_26.setGeometry(QtCore.QRect(320, 480, 4, 24))
        self.line_26.setAutoFillBackground(False)
        self.line_26.setStyleSheet(_fromUtf8("color: rgb(0, 170, 0);\n"
"background-color: rgb(0, 170, 0);\n"
"border-color: rgb(0, 170, 0);"))
        self.line_26.setFrameShadow(QtGui.QFrame.Plain)
        self.line_26.setLineWidth(0)
        self.line_26.setMidLineWidth(0)
        self.line_26.setFrameShape(QtGui.QFrame.VLine)
        self.line_26.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_26.setObjectName(_fromUtf8("line_26"))
        self.line_27 = QtGui.QFrame(self.mixtureCircuitDock)
        self.line_27.setEnabled(True)
        self.line_27.setGeometry(QtCore.QRect(390, 480, 4, 24))
        self.line_27.setAutoFillBackground(False)
        self.line_27.setStyleSheet(_fromUtf8("color: rgb(0, 170, 0);\n"
"background-color: rgb(0, 170, 0);\n"
"border-color: rgb(0, 170, 0);"))
        self.line_27.setFrameShadow(QtGui.QFrame.Plain)
        self.line_27.setLineWidth(0)
        self.line_27.setMidLineWidth(0)
        self.line_27.setFrameShape(QtGui.QFrame.VLine)
        self.line_27.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_27.setObjectName(_fromUtf8("line_27"))
        self.line_28 = QtGui.QFrame(self.mixtureCircuitDock)
        self.line_28.setEnabled(True)
        self.line_28.setGeometry(QtCore.QRect(450, 480, 4, 24))
        self.line_28.setAutoFillBackground(False)
        self.line_28.setStyleSheet(_fromUtf8("color: rgb(0, 170, 0);\n"
"background-color: rgb(0, 170, 0);\n"
"border-color: rgb(0, 170, 0);"))
        self.line_28.setFrameShadow(QtGui.QFrame.Plain)
        self.line_28.setLineWidth(0)
        self.line_28.setMidLineWidth(0)
        self.line_28.setFrameShape(QtGui.QFrame.VLine)
        self.line_28.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_28.setObjectName(_fromUtf8("line_28"))
        self.radioButton_4 = QtGui.QRadioButton(self.mixtureCircuitDock)
        self.radioButton_4.setEnabled(False)
        self.radioButton_4.setGeometry(QtCore.QRect(370, 450, 41, 22))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setPointSize(8)
        self.radioButton_4.setFont(font)
        self.radioButton_4.setMouseTracking(False)
        self.radioButton_4.setFocusPolicy(QtCore.Qt.NoFocus)
        self.radioButton_4.setAutoExclusive(False)
        self.radioButton_4.setObjectName(_fromUtf8("radioButton_4"))
        self.line_29 = QtGui.QFrame(self.mixtureCircuitDock)
        self.line_29.setEnabled(True)
        self.line_29.setGeometry(QtCore.QRect(50, 420, 181, 4))
        self.line_29.setAutoFillBackground(False)
        self.line_29.setStyleSheet(_fromUtf8("color: rgb(0, 170, 0);\n"
"background-color: rgb(0, 170, 0);\n"
"border-color: rgb(0, 170, 0);"))
        self.line_29.setFrameShadow(QtGui.QFrame.Plain)
        self.line_29.setLineWidth(0)
        self.line_29.setMidLineWidth(0)
        self.line_29.setFrameShape(QtGui.QFrame.HLine)
        self.line_29.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_29.setObjectName(_fromUtf8("line_29"))
        self.radioButton_12 = QtGui.QRadioButton(self.mixtureCircuitDock)
        self.radioButton_12.setEnabled(False)
        self.radioButton_12.setGeometry(QtCore.QRect(240, 410, 51, 22))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setPointSize(8)
        self.radioButton_12.setFont(font)
        self.radioButton_12.setMouseTracking(False)
        self.radioButton_12.setFocusPolicy(QtCore.Qt.NoFocus)
        self.radioButton_12.setAutoExclusive(False)
        self.radioButton_12.setObjectName(_fromUtf8("radioButton_12"))
        self.radioButton_9 = QtGui.QRadioButton(self.mixtureCircuitDock)
        self.radioButton_9.setEnabled(False)
        self.radioButton_9.setGeometry(QtCore.QRect(300, 450, 41, 22))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setPointSize(8)
        self.radioButton_9.setFont(font)
        self.radioButton_9.setMouseTracking(False)
        self.radioButton_9.setFocusPolicy(QtCore.Qt.NoFocus)
        self.radioButton_9.setAutoExclusive(False)
        self.radioButton_9.setObjectName(_fromUtf8("radioButton_9"))
        self.line_30 = QtGui.QFrame(self.mixtureCircuitDock)
        self.line_30.setEnabled(True)
        self.line_30.setGeometry(QtCore.QRect(320, 370, 4, 71))
        self.line_30.setAutoFillBackground(False)
        self.line_30.setStyleSheet(_fromUtf8("color: rgb(0, 170, 0);\n"
"background-color: rgb(0, 170, 0);\n"
"border-color: rgb(0, 170, 0);"))
        self.line_30.setFrameShadow(QtGui.QFrame.Plain)
        self.line_30.setLineWidth(0)
        self.line_30.setMidLineWidth(0)
        self.line_30.setFrameShape(QtGui.QFrame.VLine)
        self.line_30.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_30.setObjectName(_fromUtf8("line_30"))
        self.line_31 = QtGui.QFrame(self.mixtureCircuitDock)
        self.line_31.setEnabled(True)
        self.line_31.setGeometry(QtCore.QRect(290, 420, 31, 4))
        self.line_31.setAutoFillBackground(False)
        self.line_31.setStyleSheet(_fromUtf8("color: rgb(0, 170, 0);\n"
"background-color: rgb(0, 170, 0);\n"
"border-color: rgb(0, 170, 0);"))
        self.line_31.setFrameShadow(QtGui.QFrame.Plain)
        self.line_31.setLineWidth(0)
        self.line_31.setMidLineWidth(0)
        self.line_31.setFrameShape(QtGui.QFrame.HLine)
        self.line_31.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_31.setObjectName(_fromUtf8("line_31"))
        self.radioButton_10 = QtGui.QRadioButton(self.mixtureCircuitDock)
        self.radioButton_10.setEnabled(False)
        self.radioButton_10.setGeometry(QtCore.QRect(240, 370, 51, 22))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setPointSize(8)
        self.radioButton_10.setFont(font)
        self.radioButton_10.setMouseTracking(False)
        self.radioButton_10.setFocusPolicy(QtCore.Qt.NoFocus)
        self.radioButton_10.setAutoExclusive(False)
        self.radioButton_10.setObjectName(_fromUtf8("radioButton_10"))
        self.line_32 = QtGui.QFrame(self.mixtureCircuitDock)
        self.line_32.setEnabled(True)
        self.line_32.setGeometry(QtCore.QRect(290, 380, 31, 4))
        self.line_32.setAutoFillBackground(False)
        self.line_32.setStyleSheet(_fromUtf8("color: rgb(0, 170, 0);\n"
"background-color: rgb(0, 170, 0);\n"
"border-color: rgb(0, 170, 0);"))
        self.line_32.setFrameShadow(QtGui.QFrame.Plain)
        self.line_32.setLineWidth(0)
        self.line_32.setMidLineWidth(0)
        self.line_32.setFrameShape(QtGui.QFrame.HLine)
        self.line_32.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_32.setObjectName(_fromUtf8("line_32"))
        self.line_33 = QtGui.QFrame(self.mixtureCircuitDock)
        self.line_33.setEnabled(True)
        self.line_33.setGeometry(QtCore.QRect(210, 380, 21, 4))
        self.line_33.setAutoFillBackground(False)
        self.line_33.setStyleSheet(_fromUtf8("color: rgb(0, 170, 0);\n"
"background-color: rgb(0, 170, 0);\n"
"border-color: rgb(0, 170, 0);"))
        self.line_33.setFrameShadow(QtGui.QFrame.Plain)
        self.line_33.setLineWidth(0)
        self.line_33.setMidLineWidth(0)
        self.line_33.setFrameShape(QtGui.QFrame.HLine)
        self.line_33.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_33.setObjectName(_fromUtf8("line_33"))
        self.radioButton_14 = QtGui.QRadioButton(self.mixtureCircuitDock)
        self.radioButton_14.setEnabled(False)
        self.radioButton_14.setGeometry(QtCore.QRect(300, 340, 51, 22))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setPointSize(8)
        self.radioButton_14.setFont(font)
        self.radioButton_14.setMouseTracking(False)
        self.radioButton_14.setFocusPolicy(QtCore.Qt.NoFocus)
        self.radioButton_14.setAutoExclusive(False)
        self.radioButton_14.setObjectName(_fromUtf8("radioButton_14"))
        self.line_34 = QtGui.QFrame(self.mixtureCircuitDock)
        self.line_34.setEnabled(True)
        self.line_34.setGeometry(QtCore.QRect(320, 310, 4, 21))
        self.line_34.setAutoFillBackground(False)
        self.line_34.setStyleSheet(_fromUtf8("color: rgb(0, 170, 0);\n"
"background-color: rgb(0, 170, 0);\n"
"border-color: rgb(0, 170, 0);"))
        self.line_34.setFrameShadow(QtGui.QFrame.Plain)
        self.line_34.setLineWidth(0)
        self.line_34.setMidLineWidth(0)
        self.line_34.setFrameShape(QtGui.QFrame.VLine)
        self.line_34.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_34.setObjectName(_fromUtf8("line_34"))
        self.line_35 = QtGui.QFrame(self.mixtureCircuitDock)
        self.line_35.setEnabled(True)
        self.line_35.setGeometry(QtCore.QRect(290, 320, 31, 4))
        self.line_35.setAutoFillBackground(False)
        self.line_35.setStyleSheet(_fromUtf8("color: rgb(0, 170, 0);\n"
"background-color: rgb(0, 170, 0);\n"
"border-color: rgb(0, 170, 0);"))
        self.line_35.setFrameShadow(QtGui.QFrame.Plain)
        self.line_35.setLineWidth(0)
        self.line_35.setMidLineWidth(0)
        self.line_35.setFrameShape(QtGui.QFrame.HLine)
        self.line_35.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_35.setObjectName(_fromUtf8("line_35"))
        self.radioButton_11 = QtGui.QRadioButton(self.mixtureCircuitDock)
        self.radioButton_11.setEnabled(False)
        self.radioButton_11.setGeometry(QtCore.QRect(240, 310, 51, 22))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setPointSize(8)
        self.radioButton_11.setFont(font)
        self.radioButton_11.setMouseTracking(False)
        self.radioButton_11.setFocusPolicy(QtCore.Qt.NoFocus)
        self.radioButton_11.setAutoExclusive(False)
        self.radioButton_11.setObjectName(_fromUtf8("radioButton_11"))
        self.line_36 = QtGui.QFrame(self.mixtureCircuitDock)
        self.line_36.setEnabled(True)
        self.line_36.setGeometry(QtCore.QRect(210, 320, 21, 4))
        self.line_36.setAutoFillBackground(False)
        self.line_36.setStyleSheet(_fromUtf8("color: rgb(0, 170, 0);\n"
"background-color: rgb(0, 170, 0);\n"
"border-color: rgb(0, 170, 0);"))
        self.line_36.setFrameShadow(QtGui.QFrame.Plain)
        self.line_36.setLineWidth(0)
        self.line_36.setMidLineWidth(0)
        self.line_36.setFrameShape(QtGui.QFrame.HLine)
        self.line_36.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_36.setObjectName(_fromUtf8("line_36"))
        self.line_37 = QtGui.QFrame(self.mixtureCircuitDock)
        self.line_37.setEnabled(True)
        self.line_37.setGeometry(QtCore.QRect(390, 400, 4, 41))
        self.line_37.setAutoFillBackground(False)
        self.line_37.setStyleSheet(_fromUtf8("color: rgb(0, 170, 0);\n"
"background-color: rgb(0, 170, 0);\n"
"border-color: rgb(0, 170, 0);"))
        self.line_37.setFrameShadow(QtGui.QFrame.Plain)
        self.line_37.setLineWidth(0)
        self.line_37.setMidLineWidth(0)
        self.line_37.setFrameShape(QtGui.QFrame.VLine)
        self.line_37.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_37.setObjectName(_fromUtf8("line_37"))
        self.radioButton_15 = QtGui.QRadioButton(self.mixtureCircuitDock)
        self.radioButton_15.setEnabled(False)
        self.radioButton_15.setGeometry(QtCore.QRect(430, 450, 51, 22))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setPointSize(8)
        self.radioButton_15.setFont(font)
        self.radioButton_15.setMouseTracking(False)
        self.radioButton_15.setFocusPolicy(QtCore.Qt.NoFocus)
        self.radioButton_15.setAutoExclusive(False)
        self.radioButton_15.setObjectName(_fromUtf8("radioButton_15"))
        self.line_38 = QtGui.QFrame(self.mixtureCircuitDock)
        self.line_38.setEnabled(True)
        self.line_38.setGeometry(QtCore.QRect(450, 400, 4, 41))
        self.line_38.setAutoFillBackground(False)
        self.line_38.setStyleSheet(_fromUtf8("color: rgb(0, 170, 0);\n"
"background-color: rgb(0, 170, 0);\n"
"border-color: rgb(0, 170, 0);"))
        self.line_38.setFrameShadow(QtGui.QFrame.Plain)
        self.line_38.setLineWidth(0)
        self.line_38.setMidLineWidth(0)
        self.line_38.setFrameShape(QtGui.QFrame.VLine)
        self.line_38.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_38.setObjectName(_fromUtf8("line_38"))
        self.label_9 = QtGui.QLabel(self.mixtureCircuitDock)
        self.label_9.setGeometry(QtCore.QRect(376, 380, 31, 17))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setPointSize(8)
        self.label_9.setFont(font)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.label_10 = QtGui.QLabel(self.mixtureCircuitDock)
        self.label_10.setGeometry(QtCore.QRect(420, 380, 61, 17))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setPointSize(8)
        self.label_10.setFont(font)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.line_39 = QtGui.QFrame(self.mixtureCircuitDock)
        self.line_39.setEnabled(True)
        self.line_39.setGeometry(QtCore.QRect(390, 310, 4, 61))
        self.line_39.setAutoFillBackground(False)
        self.line_39.setStyleSheet(_fromUtf8("color: rgb(0, 170, 0);\n"
"background-color: rgb(0, 170, 0);\n"
"border-color: rgb(0, 170, 0);"))
        self.line_39.setFrameShadow(QtGui.QFrame.Plain)
        self.line_39.setLineWidth(0)
        self.line_39.setMidLineWidth(0)
        self.line_39.setFrameShape(QtGui.QFrame.VLine)
        self.line_39.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_39.setObjectName(_fromUtf8("line_39"))
        self.line_40 = QtGui.QFrame(self.mixtureCircuitDock)
        self.line_40.setEnabled(True)
        self.line_40.setGeometry(QtCore.QRect(450, 310, 4, 61))
        self.line_40.setAutoFillBackground(False)
        self.line_40.setStyleSheet(_fromUtf8("color: rgb(0, 170, 0);\n"
"background-color: rgb(0, 170, 0);\n"
"border-color: rgb(0, 170, 0);"))
        self.line_40.setFrameShadow(QtGui.QFrame.Plain)
        self.line_40.setLineWidth(0)
        self.line_40.setMidLineWidth(0)
        self.line_40.setFrameShape(QtGui.QFrame.VLine)
        self.line_40.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_40.setObjectName(_fromUtf8("line_40"))
        self.line_44 = QtGui.QFrame(self.mixtureCircuitDock)
        self.line_44.setEnabled(True)
        self.line_44.setGeometry(QtCore.QRect(100, 400, 4, 21))
        self.line_44.setAutoFillBackground(False)
        self.line_44.setStyleSheet(_fromUtf8("color: rgb(0, 170, 0);\n"
"background-color: rgb(0, 170, 0);\n"
"border-color: rgb(0, 170, 0);"))
        self.line_44.setFrameShadow(QtGui.QFrame.Plain)
        self.line_44.setLineWidth(0)
        self.line_44.setMidLineWidth(0)
        self.line_44.setFrameShape(QtGui.QFrame.VLine)
        self.line_44.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_44.setObjectName(_fromUtf8("line_44"))
        self.radioButton_8 = QtGui.QRadioButton(self.mixtureCircuitDock)
        self.radioButton_8.setEnabled(False)
        self.radioButton_8.setGeometry(QtCore.QRect(80, 370, 41, 22))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setPointSize(8)
        self.radioButton_8.setFont(font)
        self.radioButton_8.setMouseTracking(False)
        self.radioButton_8.setFocusPolicy(QtCore.Qt.NoFocus)
        self.radioButton_8.setAutoExclusive(False)
        self.radioButton_8.setObjectName(_fromUtf8("radioButton_8"))
        self.line_45 = QtGui.QFrame(self.mixtureCircuitDock)
        self.line_45.setEnabled(True)
        self.line_45.setGeometry(QtCore.QRect(100, 250, 4, 111))
        self.line_45.setAutoFillBackground(False)
        self.line_45.setStyleSheet(_fromUtf8("color: rgb(0, 170, 0);\n"
"background-color: rgb(0, 170, 0);\n"
"border-color: rgb(0, 170, 0);"))
        self.line_45.setFrameShadow(QtGui.QFrame.Plain)
        self.line_45.setLineWidth(0)
        self.line_45.setMidLineWidth(0)
        self.line_45.setFrameShape(QtGui.QFrame.VLine)
        self.line_45.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_45.setObjectName(_fromUtf8("line_45"))
        self.radioButton_13 = QtGui.QRadioButton(self.mixtureCircuitDock)
        self.radioButton_13.setEnabled(False)
        self.radioButton_13.setGeometry(QtCore.QRect(300, 280, 51, 22))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setPointSize(8)
        self.radioButton_13.setFont(font)
        self.radioButton_13.setMouseTracking(False)
        self.radioButton_13.setFocusPolicy(QtCore.Qt.NoFocus)
        self.radioButton_13.setAutoExclusive(False)
        self.radioButton_13.setObjectName(_fromUtf8("radioButton_13"))
        self.radioButton_5 = QtGui.QRadioButton(self.mixtureCircuitDock)
        self.radioButton_5.setEnabled(False)
        self.radioButton_5.setGeometry(QtCore.QRect(370, 280, 41, 22))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setPointSize(8)
        self.radioButton_5.setFont(font)
        self.radioButton_5.setMouseTracking(False)
        self.radioButton_5.setFocusPolicy(QtCore.Qt.NoFocus)
        self.radioButton_5.setAutoExclusive(False)
        self.radioButton_5.setObjectName(_fromUtf8("radioButton_5"))
        self.radioButton_16 = QtGui.QRadioButton(self.mixtureCircuitDock)
        self.radioButton_16.setEnabled(False)
        self.radioButton_16.setGeometry(QtCore.QRect(430, 280, 51, 22))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setPointSize(8)
        self.radioButton_16.setFont(font)
        self.radioButton_16.setMouseTracking(False)
        self.radioButton_16.setFocusPolicy(QtCore.Qt.NoFocus)
        self.radioButton_16.setAutoExclusive(False)
        self.radioButton_16.setObjectName(_fromUtf8("radioButton_16"))
        self.line_46 = QtGui.QFrame(self.mixtureCircuitDock)
        self.line_46.setEnabled(True)
        self.line_46.setGeometry(QtCore.QRect(320, 250, 4, 21))
        self.line_46.setAutoFillBackground(False)
        self.line_46.setStyleSheet(_fromUtf8("color: rgb(0, 170, 0);\n"
"background-color: rgb(0, 170, 0);\n"
"border-color: rgb(0, 170, 0);"))
        self.line_46.setFrameShadow(QtGui.QFrame.Plain)
        self.line_46.setLineWidth(0)
        self.line_46.setMidLineWidth(0)
        self.line_46.setFrameShape(QtGui.QFrame.VLine)
        self.line_46.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_46.setObjectName(_fromUtf8("line_46"))
        self.line_47 = QtGui.QFrame(self.mixtureCircuitDock)
        self.line_47.setEnabled(True)
        self.line_47.setGeometry(QtCore.QRect(390, 250, 4, 21))
        self.line_47.setAutoFillBackground(False)
        self.line_47.setStyleSheet(_fromUtf8("color: rgb(0, 170, 0);\n"
"background-color: rgb(0, 170, 0);\n"
"border-color: rgb(0, 170, 0);"))
        self.line_47.setFrameShadow(QtGui.QFrame.Plain)
        self.line_47.setLineWidth(0)
        self.line_47.setMidLineWidth(0)
        self.line_47.setFrameShape(QtGui.QFrame.VLine)
        self.line_47.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_47.setObjectName(_fromUtf8("line_47"))
        self.line_48 = QtGui.QFrame(self.mixtureCircuitDock)
        self.line_48.setEnabled(True)
        self.line_48.setGeometry(QtCore.QRect(450, 250, 4, 21))
        self.line_48.setAutoFillBackground(False)
        self.line_48.setStyleSheet(_fromUtf8("color: rgb(0, 170, 0);\n"
"background-color: rgb(0, 170, 0);\n"
"border-color: rgb(0, 170, 0);"))
        self.line_48.setFrameShadow(QtGui.QFrame.Plain)
        self.line_48.setLineWidth(0)
        self.line_48.setMidLineWidth(0)
        self.line_48.setFrameShape(QtGui.QFrame.VLine)
        self.line_48.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_48.setObjectName(_fromUtf8("line_48"))
        self.line_49 = QtGui.QFrame(self.mixtureCircuitDock)
        self.line_49.setEnabled(True)
        self.line_49.setGeometry(QtCore.QRect(60, 250, 391, 4))
        self.line_49.setAutoFillBackground(False)
        self.line_49.setStyleSheet(_fromUtf8("color: rgb(0, 170, 0);\n"
"background-color: rgb(0, 170, 0);\n"
"border-color: rgb(0, 170, 0);"))
        self.line_49.setFrameShadow(QtGui.QFrame.Plain)
        self.line_49.setLineWidth(0)
        self.line_49.setMidLineWidth(0)
        self.line_49.setFrameShape(QtGui.QFrame.HLine)
        self.line_49.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_49.setObjectName(_fromUtf8("line_49"))
        self.line_51 = QtGui.QFrame(self.mixtureCircuitDock)
        self.line_51.setEnabled(True)
        self.line_51.setGeometry(QtCore.QRect(290, 230, 4, 20))
        self.line_51.setAutoFillBackground(False)
        self.line_51.setStyleSheet(_fromUtf8("color: rgb(0, 170, 0);\n"
"background-color: rgb(0, 170, 0);\n"
"border-color: rgb(0, 170, 0);"))
        self.line_51.setFrameShadow(QtGui.QFrame.Plain)
        self.line_51.setLineWidth(0)
        self.line_51.setMidLineWidth(0)
        self.line_51.setFrameShape(QtGui.QFrame.VLine)
        self.line_51.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_51.setObjectName(_fromUtf8("line_51"))
        self.line_52 = QtGui.QFrame(self.mixtureCircuitDock)
        self.line_52.setEnabled(True)
        self.line_52.setGeometry(QtCore.QRect(50, 180, 4, 21))
        self.line_52.setAutoFillBackground(False)
        self.line_52.setStyleSheet(_fromUtf8("color: rgb(0, 170, 0);\n"
"background-color: rgb(0, 170, 0);\n"
"border-color: rgb(0, 170, 0);"))
        self.line_52.setFrameShadow(QtGui.QFrame.Plain)
        self.line_52.setLineWidth(0)
        self.line_52.setMidLineWidth(0)
        self.line_52.setFrameShape(QtGui.QFrame.VLine)
        self.line_52.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_52.setObjectName(_fromUtf8("line_52"))
        self.line_53 = QtGui.QFrame(self.mixtureCircuitDock)
        self.line_53.setEnabled(True)
        self.line_53.setGeometry(QtCore.QRect(50, 190, 91, 4))
        self.line_53.setAutoFillBackground(False)
        self.line_53.setStyleSheet(_fromUtf8("color: rgb(0, 170, 0);\n"
"background-color: rgb(0, 170, 0);\n"
"border-color: rgb(0, 170, 0);"))
        self.line_53.setFrameShadow(QtGui.QFrame.Plain)
        self.line_53.setLineWidth(0)
        self.line_53.setMidLineWidth(0)
        self.line_53.setFrameShape(QtGui.QFrame.HLine)
        self.line_53.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_53.setObjectName(_fromUtf8("line_53"))
        self.radioButton_0 = QtGui.QRadioButton(self.mixtureCircuitDock)
        self.radioButton_0.setEnabled(False)
        self.radioButton_0.setGeometry(QtCore.QRect(30, 150, 41, 22))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setPointSize(8)
        self.radioButton_0.setFont(font)
        self.radioButton_0.setMouseTracking(False)
        self.radioButton_0.setFocusPolicy(QtCore.Qt.NoFocus)
        self.radioButton_0.setAutoExclusive(False)
        self.radioButton_0.setObjectName(_fromUtf8("radioButton_0"))
        self.line_54 = QtGui.QFrame(self.mixtureCircuitDock)
        self.line_54.setEnabled(True)
        self.line_54.setGeometry(QtCore.QRect(50, 120, 4, 21))
        self.line_54.setAutoFillBackground(False)
        self.line_54.setStyleSheet(_fromUtf8("color: rgb(0, 170, 0);\n"
"background-color: rgb(0, 170, 0);\n"
"border-color: rgb(0, 170, 0);"))
        self.line_54.setFrameShadow(QtGui.QFrame.Plain)
        self.line_54.setLineWidth(0)
        self.line_54.setMidLineWidth(0)
        self.line_54.setFrameShape(QtGui.QFrame.VLine)
        self.line_54.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_54.setObjectName(_fromUtf8("line_54"))
        self.radioButton_S1 = QtGui.QRadioButton(self.mixtureCircuitDock)
        self.radioButton_S1.setEnabled(False)
        self.radioButton_S1.setGeometry(QtCore.QRect(30, 90, 51, 22))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setPointSize(8)
        self.radioButton_S1.setFont(font)
        self.radioButton_S1.setMouseTracking(False)
        self.radioButton_S1.setFocusPolicy(QtCore.Qt.NoFocus)
        self.radioButton_S1.setAutoExclusive(False)
        self.radioButton_S1.setObjectName(_fromUtf8("radioButton_S1"))
        self.line_58 = QtGui.QFrame(self.mixtureCircuitDock)
        self.line_58.setEnabled(True)
        self.line_58.setGeometry(QtCore.QRect(50, 60, 4, 21))
        self.line_58.setAutoFillBackground(False)
        self.line_58.setStyleSheet(_fromUtf8("color: rgb(0, 170, 0);\n"
"background-color: rgb(0, 170, 0);\n"
"border-color: rgb(0, 170, 0);"))
        self.line_58.setFrameShadow(QtGui.QFrame.Plain)
        self.line_58.setLineWidth(0)
        self.line_58.setMidLineWidth(0)
        self.line_58.setFrameShape(QtGui.QFrame.VLine)
        self.line_58.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_58.setObjectName(_fromUtf8("line_58"))
        self.line_59 = QtGui.QFrame(self.mixtureCircuitDock)
        self.line_59.setEnabled(True)
        self.line_59.setGeometry(QtCore.QRect(50, 70, 91, 4))
        self.line_59.setAutoFillBackground(False)
        self.line_59.setStyleSheet(_fromUtf8("color: rgb(0, 170, 0);\n"
"background-color: rgb(0, 170, 0);\n"
"border-color: rgb(0, 170, 0);"))
        self.line_59.setFrameShadow(QtGui.QFrame.Plain)
        self.line_59.setLineWidth(0)
        self.line_59.setMidLineWidth(0)
        self.line_59.setFrameShape(QtGui.QFrame.HLine)
        self.line_59.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_59.setObjectName(_fromUtf8("line_59"))
        self.line_60 = QtGui.QFrame(self.mixtureCircuitDock)
        self.line_60.setEnabled(True)
        self.line_60.setGeometry(QtCore.QRect(140, 70, 4, 11))
        self.line_60.setAutoFillBackground(False)
        self.line_60.setStyleSheet(_fromUtf8("color: rgb(0, 170, 0);\n"
"background-color: rgb(0, 170, 0);\n"
"border-color: rgb(0, 170, 0);"))
        self.line_60.setFrameShadow(QtGui.QFrame.Plain)
        self.line_60.setLineWidth(0)
        self.line_60.setMidLineWidth(0)
        self.line_60.setFrameShape(QtGui.QFrame.VLine)
        self.line_60.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_60.setObjectName(_fromUtf8("line_60"))
        self.radioButton_S2 = QtGui.QRadioButton(self.mixtureCircuitDock)
        self.radioButton_S2.setEnabled(False)
        self.radioButton_S2.setGeometry(QtCore.QRect(120, 90, 51, 22))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setPointSize(8)
        self.radioButton_S2.setFont(font)
        self.radioButton_S2.setMouseTracking(False)
        self.radioButton_S2.setFocusPolicy(QtCore.Qt.NoFocus)
        self.radioButton_S2.setAutoExclusive(False)
        self.radioButton_S2.setObjectName(_fromUtf8("radioButton_S2"))
        self.line_61 = QtGui.QFrame(self.mixtureCircuitDock)
        self.line_61.setEnabled(True)
        self.line_61.setGeometry(QtCore.QRect(140, 120, 4, 21))
        self.line_61.setAutoFillBackground(False)
        self.line_61.setStyleSheet(_fromUtf8("color: rgb(0, 170, 0);\n"
"background-color: rgb(0, 170, 0);\n"
"border-color: rgb(0, 170, 0);"))
        self.line_61.setFrameShadow(QtGui.QFrame.Plain)
        self.line_61.setLineWidth(0)
        self.line_61.setMidLineWidth(0)
        self.line_61.setFrameShape(QtGui.QFrame.VLine)
        self.line_61.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_61.setObjectName(_fromUtf8("line_61"))
        self.radioButton_1 = QtGui.QRadioButton(self.mixtureCircuitDock)
        self.radioButton_1.setEnabled(False)
        self.radioButton_1.setGeometry(QtCore.QRect(120, 150, 41, 22))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setPointSize(8)
        self.radioButton_1.setFont(font)
        self.radioButton_1.setMouseTracking(False)
        self.radioButton_1.setFocusPolicy(QtCore.Qt.NoFocus)
        self.radioButton_1.setAutoExclusive(False)
        self.radioButton_1.setObjectName(_fromUtf8("radioButton_1"))
        self.line_62 = QtGui.QFrame(self.mixtureCircuitDock)
        self.line_62.setEnabled(True)
        self.line_62.setGeometry(QtCore.QRect(140, 180, 4, 14))
        self.line_62.setAutoFillBackground(False)
        self.line_62.setStyleSheet(_fromUtf8("color: rgb(0, 170, 0);\n"
"background-color: rgb(0, 170, 0);\n"
"border-color: rgb(0, 170, 0);"))
        self.line_62.setFrameShadow(QtGui.QFrame.Plain)
        self.line_62.setLineWidth(0)
        self.line_62.setMidLineWidth(0)
        self.line_62.setFrameShape(QtGui.QFrame.VLine)
        self.line_62.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_62.setObjectName(_fromUtf8("line_62"))
        self.label_11 = QtGui.QLabel(self.mixtureCircuitDock)
        self.label_11.setGeometry(QtCore.QRect(30, 40, 41, 17))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setPointSize(8)
        font.setItalic(False)
        self.label_11.setFont(font)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.line_63 = QtGui.QFrame(self.mixtureCircuitDock)
        self.line_63.setEnabled(True)
        self.line_63.setGeometry(QtCore.QRect(50, 10, 4, 21))
        self.line_63.setAutoFillBackground(False)
        self.line_63.setStyleSheet(_fromUtf8("color: rgb(0, 170, 0);\n"
"background-color: rgb(0, 170, 0);\n"
"border-color: rgb(0, 170, 0);"))
        self.line_63.setFrameShadow(QtGui.QFrame.Plain)
        self.line_63.setLineWidth(0)
        self.line_63.setMidLineWidth(0)
        self.line_63.setFrameShape(QtGui.QFrame.VLine)
        self.line_63.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_63.setObjectName(_fromUtf8("line_63"))
        self.line_64 = QtGui.QFrame(self.mixtureCircuitDock)
        self.line_64.setEnabled(True)
        self.line_64.setGeometry(QtCore.QRect(50, 20, 151, 4))
        self.line_64.setAutoFillBackground(False)
        self.line_64.setStyleSheet(_fromUtf8("color: rgb(0, 170, 0);\n"
"background-color: rgb(0, 170, 0);\n"
"border-color: rgb(0, 170, 0);"))
        self.line_64.setFrameShadow(QtGui.QFrame.Plain)
        self.line_64.setLineWidth(0)
        self.line_64.setMidLineWidth(0)
        self.line_64.setFrameShape(QtGui.QFrame.HLine)
        self.line_64.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_64.setObjectName(_fromUtf8("line_64"))
        self.line_65 = QtGui.QFrame(self.mixtureCircuitDock)
        self.line_65.setEnabled(True)
        self.line_65.setGeometry(QtCore.QRect(200, 20, 4, 101))
        self.line_65.setAutoFillBackground(False)
        self.line_65.setStyleSheet(_fromUtf8("color: rgb(0, 170, 0);\n"
"background-color: rgb(0, 170, 0);\n"
"border-color: rgb(0, 170, 0);"))
        self.line_65.setFrameShadow(QtGui.QFrame.Plain)
        self.line_65.setLineWidth(0)
        self.line_65.setMidLineWidth(0)
        self.line_65.setFrameShape(QtGui.QFrame.VLine)
        self.line_65.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_65.setObjectName(_fromUtf8("line_65"))
        self.radioButton_17 = QtGui.QRadioButton(self.mixtureCircuitDock)
        self.radioButton_17.setEnabled(False)
        self.radioButton_17.setGeometry(QtCore.QRect(180, 130, 51, 22))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setPointSize(8)
        self.radioButton_17.setFont(font)
        self.radioButton_17.setMouseTracking(False)
        self.radioButton_17.setFocusPolicy(QtCore.Qt.NoFocus)
        self.radioButton_17.setAutoExclusive(False)
        self.radioButton_17.setObjectName(_fromUtf8("radioButton_17"))
        self.line_66 = QtGui.QFrame(self.mixtureCircuitDock)
        self.line_66.setEnabled(True)
        self.line_66.setGeometry(QtCore.QRect(200, 160, 4, 12))
        self.line_66.setAutoFillBackground(False)
        self.line_66.setStyleSheet(_fromUtf8("color: rgb(0, 170, 0);\n"
"background-color: rgb(0, 170, 0);\n"
"border-color: rgb(0, 170, 0);"))
        self.line_66.setFrameShadow(QtGui.QFrame.Plain)
        self.line_66.setLineWidth(0)
        self.line_66.setMidLineWidth(0)
        self.line_66.setFrameShape(QtGui.QFrame.VLine)
        self.line_66.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_66.setObjectName(_fromUtf8("line_66"))
        self.line_67 = QtGui.QFrame(self.mixtureCircuitDock)
        self.line_67.setEnabled(True)
        self.line_67.setGeometry(QtCore.QRect(200, 170, 134, 4))
        self.line_67.setAutoFillBackground(False)
        self.line_67.setStyleSheet(_fromUtf8("color: rgb(0, 170, 0);\n"
"background-color: rgb(0, 170, 0);\n"
"border-color: rgb(0, 170, 0);"))
        self.line_67.setFrameShadow(QtGui.QFrame.Plain)
        self.line_67.setLineWidth(0)
        self.line_67.setMidLineWidth(0)
        self.line_67.setFrameShape(QtGui.QFrame.HLine)
        self.line_67.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_67.setObjectName(_fromUtf8("line_67"))
        self.line_68 = QtGui.QFrame(self.mixtureCircuitDock)
        self.line_68.setEnabled(True)
        self.line_68.setGeometry(QtCore.QRect(250, 130, 4, 41))
        self.line_68.setAutoFillBackground(False)
        self.line_68.setStyleSheet(_fromUtf8("color: rgb(0, 170, 0);\n"
"background-color: rgb(0, 170, 0);\n"
"border-color: rgb(0, 170, 0);"))
        self.line_68.setFrameShadow(QtGui.QFrame.Plain)
        self.line_68.setLineWidth(0)
        self.line_68.setMidLineWidth(0)
        self.line_68.setFrameShape(QtGui.QFrame.VLine)
        self.line_68.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_68.setObjectName(_fromUtf8("line_68"))
        self.line_69 = QtGui.QFrame(self.mixtureCircuitDock)
        self.line_69.setEnabled(True)
        self.line_69.setGeometry(QtCore.QRect(330, 130, 4, 41))
        self.line_69.setAutoFillBackground(False)
        self.line_69.setStyleSheet(_fromUtf8("color: rgb(0, 170, 0);\n"
"background-color: rgb(0, 170, 0);\n"
"border-color: rgb(0, 170, 0);"))
        self.line_69.setFrameShadow(QtGui.QFrame.Plain)
        self.line_69.setLineWidth(0)
        self.line_69.setMidLineWidth(0)
        self.line_69.setFrameShape(QtGui.QFrame.VLine)
        self.line_69.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_69.setObjectName(_fromUtf8("line_69"))
        self.line_70 = QtGui.QFrame(self.mixtureCircuitDock)
        self.line_70.setEnabled(True)
        self.line_70.setGeometry(QtCore.QRect(290, 170, 4, 21))
        self.line_70.setAutoFillBackground(False)
        self.line_70.setStyleSheet(_fromUtf8("color: rgb(0, 170, 0);\n"
"background-color: rgb(0, 170, 0);\n"
"border-color: rgb(0, 170, 0);"))
        self.line_70.setFrameShadow(QtGui.QFrame.Plain)
        self.line_70.setLineWidth(0)
        self.line_70.setMidLineWidth(0)
        self.line_70.setFrameShape(QtGui.QFrame.VLine)
        self.line_70.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_70.setObjectName(_fromUtf8("line_70"))
        self.radioButton_6 = QtGui.QRadioButton(self.mixtureCircuitDock)
        self.radioButton_6.setEnabled(False)
        self.radioButton_6.setGeometry(QtCore.QRect(230, 100, 41, 22))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setPointSize(8)
        self.radioButton_6.setFont(font)
        self.radioButton_6.setMouseTracking(False)
        self.radioButton_6.setFocusPolicy(QtCore.Qt.NoFocus)
        self.radioButton_6.setAutoExclusive(False)
        self.radioButton_6.setObjectName(_fromUtf8("radioButton_6"))
        self.radioButton_7 = QtGui.QRadioButton(self.mixtureCircuitDock)
        self.radioButton_7.setEnabled(False)
        self.radioButton_7.setGeometry(QtCore.QRect(310, 100, 41, 22))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setPointSize(8)
        self.radioButton_7.setFont(font)
        self.radioButton_7.setMouseTracking(False)
        self.radioButton_7.setFocusPolicy(QtCore.Qt.NoFocus)
        self.radioButton_7.setAutoExclusive(False)
        self.radioButton_7.setObjectName(_fromUtf8("radioButton_7"))
        self.line_71 = QtGui.QFrame(self.mixtureCircuitDock)
        self.line_71.setEnabled(True)
        self.line_71.setGeometry(QtCore.QRect(250, 10, 4, 81))
        self.line_71.setAutoFillBackground(False)
        self.line_71.setStyleSheet(_fromUtf8("color: rgb(0, 170, 0);\n"
"background-color: rgb(0, 170, 0);\n"
"border-color: rgb(0, 170, 0);"))
        self.line_71.setFrameShadow(QtGui.QFrame.Plain)
        self.line_71.setLineWidth(0)
        self.line_71.setMidLineWidth(0)
        self.line_71.setFrameShape(QtGui.QFrame.VLine)
        self.line_71.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_71.setObjectName(_fromUtf8("line_71"))
        self.line_72 = QtGui.QFrame(self.mixtureCircuitDock)
        self.line_72.setEnabled(True)
        self.line_72.setGeometry(QtCore.QRect(330, 10, 4, 81))
        self.line_72.setAutoFillBackground(False)
        self.line_72.setStyleSheet(_fromUtf8("color: rgb(0, 170, 0);\n"
"background-color: rgb(0, 170, 0);\n"
"border-color: rgb(0, 170, 0);"))
        self.line_72.setFrameShadow(QtGui.QFrame.Plain)
        self.line_72.setLineWidth(0)
        self.line_72.setMidLineWidth(0)
        self.line_72.setFrameShape(QtGui.QFrame.VLine)
        self.line_72.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_72.setObjectName(_fromUtf8("line_72"))
        self.label_12 = QtGui.QLabel(self.mixtureCircuitDock)
        self.label_12.setGeometry(QtCore.QRect(60, 0, 51, 17))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setPointSize(6)
        self.label_12.setFont(font)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.label_13 = QtGui.QLabel(self.mixtureCircuitDock)
        self.label_13.setGeometry(QtCore.QRect(260, 20, 51, 17))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setPointSize(6)
        self.label_13.setFont(font)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.label_14 = QtGui.QLabel(self.mixtureCircuitDock)
        self.label_14.setGeometry(QtCore.QRect(340, 20, 51, 17))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setPointSize(6)
        self.label_14.setFont(font)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.line_42 = QtGui.QFrame(self.centralwidget)
        self.line_42.setEnabled(True)
        self.line_42.setGeometry(QtCore.QRect(420, 340, 4, 34))
        self.line_42.setAutoFillBackground(False)
        self.line_42.setStyleSheet(_fromUtf8("color: rgb(255, 255, 0);\n"
"border-color: rgb(255, 255, 0);\n"
"background-color: rgb(255, 255, 0);"))
        self.line_42.setFrameShadow(QtGui.QFrame.Plain)
        self.line_42.setLineWidth(0)
        self.line_42.setMidLineWidth(0)
        self.line_42.setFrameShape(QtGui.QFrame.VLine)
        self.line_42.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_42.setObjectName(_fromUtf8("line_42"))
        self.radioButton_A9 = QtGui.QRadioButton(self.centralwidget)
        self.radioButton_A9.setEnabled(False)
        self.radioButton_A9.setGeometry(QtCore.QRect(400, 310, 51, 22))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setPointSize(8)
        self.radioButton_A9.setFont(font)
        self.radioButton_A9.setMouseTracking(False)
        self.radioButton_A9.setFocusPolicy(QtCore.Qt.NoFocus)
        self.radioButton_A9.setAutoExclusive(False)
        self.radioButton_A9.setObjectName(_fromUtf8("radioButton_A9"))
        self.line_43 = QtGui.QFrame(self.centralwidget)
        self.line_43.setEnabled(True)
        self.line_43.setGeometry(QtCore.QRect(420, 270, 4, 31))
        self.line_43.setAutoFillBackground(False)
        self.line_43.setStyleSheet(_fromUtf8("color: rgb(0, 170, 0);\n"
"background-color: rgb(0, 170, 0);\n"
"border-color: rgb(0, 170, 0);"))
        self.line_43.setFrameShadow(QtGui.QFrame.Plain)
        self.line_43.setLineWidth(0)
        self.line_43.setMidLineWidth(0)
        self.line_43.setFrameShape(QtGui.QFrame.VLine)
        self.line_43.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_43.setObjectName(_fromUtf8("line_43"))
        self.radioButton_A10 = QtGui.QRadioButton(self.centralwidget)
        self.radioButton_A10.setEnabled(False)
        self.radioButton_A10.setGeometry(QtCore.QRect(400, 30, 51, 22))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setPointSize(8)
        self.radioButton_A10.setFont(font)
        self.radioButton_A10.setMouseTracking(False)
        self.radioButton_A10.setFocusPolicy(QtCore.Qt.NoFocus)
        self.radioButton_A10.setAutoExclusive(False)
        self.radioButton_A10.setObjectName(_fromUtf8("radioButton_A10"))
        self.line_57 = QtGui.QFrame(self.centralwidget)
        self.line_57.setEnabled(True)
        self.line_57.setGeometry(QtCore.QRect(460, 40, 61, 4))
        self.line_57.setAutoFillBackground(False)
        self.line_57.setStyleSheet(_fromUtf8("color: rgb(0, 170, 0);\n"
"background-color: rgb(0, 170, 0);\n"
"border-color: rgb(0, 170, 0);"))
        self.line_57.setFrameShadow(QtGui.QFrame.Plain)
        self.line_57.setLineWidth(0)
        self.line_57.setMidLineWidth(0)
        self.line_57.setFrameShape(QtGui.QFrame.HLine)
        self.line_57.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_57.setObjectName(_fromUtf8("line_57"))
        self.line_50 = QtGui.QFrame(self.centralwidget)
        self.line_50.setEnabled(True)
        self.line_50.setGeometry(QtCore.QRect(420, 270, 91, 4))
        self.line_50.setAutoFillBackground(False)
        self.line_50.setStyleSheet(_fromUtf8("color: rgb(0, 170, 0);\n"
"background-color: rgb(0, 170, 0);\n"
"border-color: rgb(0, 170, 0);"))
        self.line_50.setFrameShadow(QtGui.QFrame.Plain)
        self.line_50.setLineWidth(0)
        self.line_50.setMidLineWidth(0)
        self.line_50.setFrameShape(QtGui.QFrame.HLine)
        self.line_50.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_50.setObjectName(_fromUtf8("line_50"))
        self.maxiGaugeDock = QtGui.QGroupBox(self.centralwidget)
        self.maxiGaugeDock.setGeometry(QtCore.QRect(381, 565, 181, 125))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setPointSize(9)
        self.maxiGaugeDock.setFont(font)
        self.maxiGaugeDock.setObjectName(_fromUtf8("maxiGaugeDock"))
        self.lcdNumber_IVC = QtGui.QLCDNumber(self.maxiGaugeDock)
        self.lcdNumber_IVC.setGeometry(QtCore.QRect(50, 30, 64, 23))
        self.lcdNumber_IVC.setStyleSheet(_fromUtf8("background-color: rgb(0, 0, 0);\n"
"color: rgb(0, 255, 0);\n"
"font: 10pt \"Arial\";"))
        self.lcdNumber_IVC.setSmallDecimalPoint(True)
        self.lcdNumber_IVC.setNumDigits(6)
        self.lcdNumber_IVC.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.lcdNumber_IVC.setObjectName(_fromUtf8("lcdNumber_IVC"))
        self.lcdNumber_STIL = QtGui.QLCDNumber(self.maxiGaugeDock)
        self.lcdNumber_STIL.setGeometry(QtCore.QRect(50, 70, 64, 23))
        self.lcdNumber_STIL.setStyleSheet(_fromUtf8("background-color: rgb(0, 0, 0);\n"
"color: rgb(0, 255, 0);\n"
"font: 10pt \"Arial\";"))
        self.lcdNumber_STIL.setSmallDecimalPoint(True)
        self.lcdNumber_STIL.setNumDigits(6)
        self.lcdNumber_STIL.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.lcdNumber_STIL.setObjectName(_fromUtf8("lcdNumber_STIL"))
        self.label = QtGui.QLabel(self.maxiGaugeDock)
        self.label.setGeometry(QtCore.QRect(10, 33, 31, 17))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setPointSize(8)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.label_2 = QtGui.QLabel(self.maxiGaugeDock)
        self.label_2.setGeometry(QtCore.QRect(10, 73, 41, 17))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setPointSize(8)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_3 = QtGui.QLabel(self.maxiGaugeDock)
        self.label_3.setGeometry(QtCore.QRect(120, 38, 51, 17))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setPointSize(8)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_4 = QtGui.QLabel(self.maxiGaugeDock)
        self.label_4.setGeometry(QtCore.QRect(120, 78, 51, 17))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setPointSize(8)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.systemStatusDock = QtGui.QGroupBox(self.centralwidget)
        self.systemStatusDock.setGeometry(QtCore.QRect(10, 565, 361, 125))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setPointSize(9)
        self.systemStatusDock.setFont(font)
        self.systemStatusDock.setObjectName(_fromUtf8("systemStatusDock"))
        self.radioButton_Start = QtGui.QRadioButton(self.systemStatusDock)
        self.radioButton_Start.setEnabled(False)
        self.radioButton_Start.setGeometry(QtCore.QRect(10, 30, 81, 22))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        self.radioButton_Start.setFont(font)
        self.radioButton_Start.setMouseTracking(False)
        self.radioButton_Start.setFocusPolicy(QtCore.Qt.NoFocus)
        self.radioButton_Start.setChecked(False)
        self.radioButton_Start.setAutoRepeat(False)
        self.radioButton_Start.setAutoExclusive(False)
        self.radioButton_Start.setAutoRepeatInterval(500)
        self.radioButton_Start.setObjectName(_fromUtf8("radioButton_Start"))
        self.radioButton_He3 = QtGui.QRadioButton(self.systemStatusDock)
        self.radioButton_He3.setEnabled(False)
        self.radioButton_He3.setGeometry(QtCore.QRect(280, 60, 61, 22))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        self.radioButton_He3.setFont(font)
        self.radioButton_He3.setMouseTracking(False)
        self.radioButton_He3.setFocusPolicy(QtCore.Qt.NoFocus)
        self.radioButton_He3.setAutoExclusive(False)
        self.radioButton_He3.setObjectName(_fromUtf8("radioButton_He3"))
        self.radioButton_He4 = QtGui.QRadioButton(self.systemStatusDock)
        self.radioButton_He4.setEnabled(False)
        self.radioButton_He4.setGeometry(QtCore.QRect(280, 30, 61, 22))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        self.radioButton_He4.setFont(font)
        self.radioButton_He4.setMouseTracking(False)
        self.radioButton_He4.setFocusPolicy(QtCore.Qt.NoFocus)
        self.radioButton_He4.setAutoExclusive(False)
        self.radioButton_He4.setObjectName(_fromUtf8("radioButton_He4"))
        self.radioButton_Norm = QtGui.QRadioButton(self.systemStatusDock)
        self.radioButton_Norm.setEnabled(False)
        self.radioButton_Norm.setGeometry(QtCore.QRect(120, 30, 161, 22))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        self.radioButton_Norm.setFont(font)
        self.radioButton_Norm.setMouseTracking(False)
        self.radioButton_Norm.setFocusPolicy(QtCore.Qt.NoFocus)
        self.radioButton_Norm.setAutoExclusive(False)
        self.radioButton_Norm.setObjectName(_fromUtf8("radioButton_Norm"))
        self.radioButton_Rec = QtGui.QRadioButton(self.systemStatusDock)
        self.radioButton_Rec.setEnabled(False)
        self.radioButton_Rec.setGeometry(QtCore.QRect(120, 60, 91, 22))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        self.radioButton_Rec.setFont(font)
        self.radioButton_Rec.setMouseTracking(False)
        self.radioButton_Rec.setFocusPolicy(QtCore.Qt.NoFocus)
        self.radioButton_Rec.setAutoExclusive(False)
        self.radioButton_Rec.setObjectName(_fromUtf8("radioButton_Rec"))
        self.radioButton_Reset = QtGui.QRadioButton(self.systemStatusDock)
        self.radioButton_Reset.setEnabled(False)
        self.radioButton_Reset.setGeometry(QtCore.QRect(10, 60, 81, 22))
        self.radioButton_Reset.setMouseTracking(False)
        self.radioButton_Reset.setFocusPolicy(QtCore.Qt.NoFocus)
        self.radioButton_Reset.setAutoExclusive(False)
        self.radioButton_Reset.setObjectName(_fromUtf8("radioButton_Reset"))
        self.radioButton_Auto = QtGui.QRadioButton(self.systemStatusDock)
        self.radioButton_Auto.setEnabled(False)
        self.radioButton_Auto.setGeometry(QtCore.QRect(10, 90, 71, 22))
        self.radioButton_Auto.setMouseTracking(False)
        self.radioButton_Auto.setFocusPolicy(QtCore.Qt.NoFocus)
        self.radioButton_Auto.setAutoExclusive(False)
        self.radioButton_Auto.setObjectName(_fromUtf8("radioButton_Auto"))
        self.radioButton_Aux1 = QtGui.QRadioButton(self.systemStatusDock)
        self.radioButton_Aux1.setEnabled(False)
        self.radioButton_Aux1.setGeometry(QtCore.QRect(120, 90, 71, 22))
        self.radioButton_Aux1.setMouseTracking(False)
        self.radioButton_Aux1.setFocusPolicy(QtCore.Qt.NoFocus)
        self.radioButton_Aux1.setAutoExclusive(False)
        self.radioButton_Aux1.setObjectName(_fromUtf8("radioButton_Aux1"))
        self.line_73 = QtGui.QFrame(self.centralwidget)
        self.line_73.setGeometry(QtCore.QRect(10, 550, 941, 20))
        self.line_73.setFrameShape(QtGui.QFrame.HLine)
        self.line_73.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_73.setObjectName(_fromUtf8("line_73"))
        self.logDock = QtGui.QGroupBox(self.centralwidget)
        self.logDock.setGeometry(QtCore.QRect(572, 565, 371, 101))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setPointSize(9)
        self.logDock.setFont(font)
        self.logDock.setObjectName(_fromUtf8("logDock"))
        self.textBrowser = QtGui.QTextBrowser(self.logDock)
        self.textBrowser.setGeometry(QtCore.QRect(10, 30, 361, 61))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(8)
        self.textBrowser.setFont(font)
        self.textBrowser.setObjectName(_fromUtf8("textBrowser"))
        self.startButton = QtGui.QPushButton(self.centralwidget)
        self.startButton.setGeometry(QtCore.QRect(580, 670, 95, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setPointSize(9)
        self.startButton.setFont(font)
        self.startButton.setObjectName(_fromUtf8("startButton"))
        self.stopButton = QtGui.QPushButton(self.centralwidget)
        self.stopButton.setEnabled(False)
        self.stopButton.setGeometry(QtCore.QRect(690, 670, 95, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setPointSize(9)
        self.stopButton.setFont(font)
        self.stopButton.setObjectName(_fromUtf8("stopButton"))
        self.line_41 = QtGui.QFrame(self.centralwidget)
        self.line_41.setEnabled(True)
        self.line_41.setGeometry(QtCore.QRect(310, 370, 111, 4))
        self.line_41.setAutoFillBackground(False)
        self.line_41.setStyleSheet(_fromUtf8("color: rgb(255, 255, 0);\n"
"border-color: rgb(255, 255, 0);\n"
"background-color: rgb(255, 255, 0);"))
        self.line_41.setFrameShadow(QtGui.QFrame.Plain)
        self.line_41.setLineWidth(0)
        self.line_41.setMidLineWidth(0)
        self.line_41.setFrameShape(QtGui.QFrame.HLine)
        self.line_41.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_41.setObjectName(_fromUtf8("line_41"))
        self.line_56 = QtGui.QFrame(self.centralwidget)
        self.line_56.setEnabled(True)
        self.line_56.setGeometry(QtCore.QRect(310, 40, 81, 4))
        self.line_56.setAutoFillBackground(False)
        self.line_56.setStyleSheet(_fromUtf8("color: rgb(255, 255, 0);\n"
"border-color: rgb(255, 255, 0);\n"
"background-color: rgb(255, 255, 0);"))
        self.line_56.setFrameShadow(QtGui.QFrame.Plain)
        self.line_56.setLineWidth(0)
        self.line_56.setMidLineWidth(0)
        self.line_56.setFrameShape(QtGui.QFrame.HLine)
        self.line_56.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_56.setObjectName(_fromUtf8("line_56"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 962, 25))
        self.menubar.setNativeMenuBar(False)
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuSettings = QtGui.QMenu(self.menubar)
        self.menuSettings.setObjectName(_fromUtf8("menuSettings"))
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionNewPorts = QtGui.QAction(MainWindow)
        self.actionNewPorts.setObjectName(_fromUtf8("actionNewPorts"))
        self.actionLogs = QtGui.QAction(MainWindow)
        self.actionLogs.setEnabled(False)
        self.actionLogs.setObjectName(_fromUtf8("actionLogs"))
        self.actionAbout = QtGui.QAction(MainWindow)
        self.actionAbout.setObjectName(_fromUtf8("actionAbout"))
        self.menuSettings.addAction(self.actionLogs)
        self.menuSettings.addAction(self.actionNewPorts)
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuSettings.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "GHS-DRS1000 Monitor", None))
        self.label_P1.setText(_translate("MainWindow", "P1", None))
        self.label_P2.setText(_translate("MainWindow", "P2", None))
        self.label_P3.setText(_translate("MainWindow", "P3", None))
        self.radioButton_A1.setText(_translate("MainWindow", "A1", None))
        self.radioButton_A2.setText(_translate("MainWindow", "A2", None))
        self.radioButton_S5.setText(_translate("MainWindow", "S5", None))
        self.radioButton_A0.setText(_translate("MainWindow", "A0", None))
        self.radioButton_A4.setText(_translate("MainWindow", "A4", None))
        self.radioButton_A5.setText(_translate("MainWindow", "A5", None))
        self.radioButton_A3.setText(_translate("MainWindow", "A3", None))
        self.radioButton_A6.setText(_translate("MainWindow", "A6", None))
        self.radioButton_A7.setText(_translate("MainWindow", "A7", None))
        self.radioButton_A8.setText(_translate("MainWindow", "A8", None))
        self.radioButton_S4.setText(_translate("MainWindow", "S4", None))
        self.label_5.setText(_translate("MainWindow", "TO RECOVERY", None))
        self.label_6.setText(_translate("MainWindow", "FROM DEWAR", None))
        self.label_7.setText(_translate("MainWindow", "FROM 1K POT", None))
        self.label_8.setText(_translate("MainWindow", "FROM IVC", None))
        self.label_P4.setText(_translate("MainWindow", "P4", None))
        self.label_P5.setText(_translate("MainWindow", "P5", None))
        self.label_P6.setText(_translate("MainWindow", "DUMP-4He", None))
        self.label_P7.setText(_translate("MainWindow", "DUMP-3He", None))
        self.label_P8.setText(_translate("MainWindow", "FLOW", None))
        self.radioButton_2.setText(_translate("MainWindow", "2", None))
        self.radioButton_3.setText(_translate("MainWindow", "3", None))
        self.radioButton_S3.setText(_translate("MainWindow", "S3", None))
        self.radioButton_4.setText(_translate("MainWindow", "4", None))
        self.radioButton_12.setText(_translate("MainWindow", "12", None))
        self.radioButton_9.setText(_translate("MainWindow", "9", None))
        self.radioButton_10.setText(_translate("MainWindow", "10", None))
        self.radioButton_14.setText(_translate("MainWindow", "14", None))
        self.radioButton_11.setText(_translate("MainWindow", "11", None))
        self.radioButton_15.setText(_translate("MainWindow", "15", None))
        self.label_9.setText(_translate("MainWindow", "TRAP", None))
        self.label_10.setText(_translate("MainWindow", "AUX TRAP", None))
        self.radioButton_8.setText(_translate("MainWindow", "8", None))
        self.radioButton_13.setText(_translate("MainWindow", "13", None))
        self.radioButton_5.setText(_translate("MainWindow", "5", None))
        self.radioButton_16.setText(_translate("MainWindow", "16", None))
        self.radioButton_0.setText(_translate("MainWindow", "0", None))
        self.radioButton_S1.setText(_translate("MainWindow", "S1", None))
        self.radioButton_S2.setText(_translate("MainWindow", "S2", None))
        self.radioButton_1.setText(_translate("MainWindow", "1", None))
        self.label_11.setText(_translate("MainWindow", "AUX-1", None))
        self.radioButton_17.setText(_translate("MainWindow", "17", None))
        self.radioButton_6.setText(_translate("MainWindow", "6", None))
        self.radioButton_7.setText(_translate("MainWindow", "7", None))
        self.label_12.setText(_translate("MainWindow", "FROM STILL", None))
        self.label_13.setText(_translate("MainWindow", "TO 3He IN-1", None))
        self.label_14.setText(_translate("MainWindow", "TO 3He IN-2", None))
        self.radioButton_A9.setText(_translate("MainWindow", "A9", None))
        self.radioButton_A10.setText(_translate("MainWindow", "A10", None))
        self.maxiGaugeDock.setTitle(_translate("MainWindow", "MaxiGauge", None))
        self.label.setText(_translate("MainWindow", "IVC", None))
        self.label_2.setText(_translate("MainWindow", "STILL", None))
        self.label_3.setText(_translate("MainWindow", "mbar", None))
        self.label_4.setText(_translate("MainWindow", "mbar", None))
        self.systemStatusDock.setTitle(_translate("MainWindow", "System Status", None))
        self.radioButton_Start.setText(_translate("MainWindow", "START", None))
        self.radioButton_He3.setText(_translate("MainWindow", "3He", None))
        self.radioButton_He4.setText(_translate("MainWindow", "4He", None))
        self.radioButton_Norm.setText(_translate("MainWindow", "Normal Circulation", None))
        self.radioButton_Rec.setText(_translate("MainWindow", "Recovery", None))
        self.radioButton_Reset.setText(_translate("MainWindow", "RESET", None))
        self.radioButton_Auto.setText(_translate("MainWindow", "AUTO", None))
        self.radioButton_Aux1.setText(_translate("MainWindow", "AUX-1", None))
        self.logDock.setTitle(_translate("MainWindow", "Log", None))
        self.startButton.setText(_translate("MainWindow", "&Start", None))
        self.stopButton.setText(_translate("MainWindow", "S&top", None))
        self.menuSettings.setTitle(_translate("MainWindow", "S&ettings", None))
        self.menuHelp.setTitle(_translate("MainWindow", "&?", None))
        self.actionNewPorts.setText(_translate("MainWindow", "&Ports...", None))
        self.actionLogs.setText(_translate("MainWindow", "&Logs...", None))
        self.actionAbout.setText(_translate("MainWindow", "&About", None))

